[package]
edition = "2021"
name = "cptra-imgtool"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
env_logger.workspace = true
hex.workspace = true
log.workspace = true
memoffset.workspace = true
once_cell.workspace = true
p384.workspace = true
serde.workspace = true
serde_derive.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
zerocopy.workspace = true

[workspace]
members = [
  "tools/cptra_2x/auth-manifest/app",
  "tools/cptra_1x/auth-manifest/app",
]

[workspace.dependencies]
anyhow = "=1.0.102"
arbitrary = {version = "=1.4.2", features = ["derive"]}
bitfield = "=0.14.0"
bitflags = "=2.10.0"
cfg-if = "=1.0.4"
chrono = "=0.4.44"
clap = {version = "=4.5.60", default-features = false, features = ["std"]}
colored = "=2.2.0"
elf = "=0.7.4"
env_logger = "=0.11.9"
getrandom = "=0.3.4"
hex = "=0.4.3"
libc = "=0.2.185"
log = "=0.4.29"
memoffset = "=0.9.1"
num-bigint = "=0.4.3"
once_cell = "=1.21.3"
openssl = {version = "=0.10.72", features = ["vendored"]}
p384 = {version = "=0.13.1", features = ["ecdsa"]}
proc-macro2 = "=1.0.105"
quote = "=1.0.43"
serde = "=1.0.228"
serde_derive = "=1.0.228"
sha2 = "=0.10.9"
simple_asn1 = "=0.6.3"
syn = "=1.0.109"
tempfile = "=3.26.0"
time = "=0.3.44"
toml = "=0.7.8"
ufmt = {git = "https://github.com/korran/ufmt.git", rev = "1d0743c1ffffc68bc05ca8eeb81c166192863f33", features = ["inline"]}
zerocopy = {version = "=0.8.40", features = ["derive"]}
zeroize = {version = "=1.8.2", default-features = false, features = ["zeroize_derive"]}

caliptra-auth-man-gen = {path = "tools/cptra_1x/auth-manifest/gen", default-features = false}
caliptra-auth-man-gen-2x = {path = "tools/cptra_2x/auth-manifest/gen", default-features = false}
caliptra-auth-man-types = {path = "tools/cptra_1x/auth-manifest/types", default-features = false}
caliptra-auth-man-types-2x = {path = "tools/cptra_2x/auth-manifest/types", default-features = false}

caliptra-drivers = {package = "caliptra-drivers", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}
caliptra-error = {package = "caliptra-error", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9", default-features = false}
caliptra-image-crypto = {package = "caliptra-image-crypto", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}
caliptra-image-elf = {package = "caliptra-image-elf", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}
caliptra-image-gen = {package = "caliptra-image-gen", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}
caliptra-image-serde = {package = "caliptra-image-serde", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}
caliptra-image-types = {package = "caliptra-image-types", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9", default-features = false}
caliptra-lms-types = {package = "caliptra-lms-types", git = "https://github.com/chipsalliance/caliptra-sw", rev = "951209a31c4373658f89e4b1211f3a557731c7d9"}

caliptra-drivers-2x = {package = "caliptra-drivers", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-error-2x = {package = "caliptra-error", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35", default-features = false}
caliptra-image-crypto-2x = {package = "caliptra-image-crypto", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-image-elf-2x = {package = "caliptra-image-elf", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-image-fake-keys-2x = {package = "caliptra-image-fake-keys", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-image-gen-2x = {package = "caliptra-image-gen", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-image-serde-2x = {package = "caliptra-image-serde", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}
caliptra-image-types-2x = {package = "caliptra-image-types", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35", default-features = false}
caliptra-lms-types-2x = {package = "caliptra-lms-types", git = "https://github.com/chipsalliance/caliptra-sw", rev = "879608b901cc60a68f4e52441e3c494605d08f35"}

[patch.crates-io]
# Fork of https://github.com/teythoon/rust-openssl.git/justus/pqc
openssl = {git = "https://github.com/clundin25/rust-openssl.git", rev = "4ada1c1d7c264e052e7bb71ecddbd196a5c2a0c7"}# MLDSA
