[package]
name = "cptra-imgtool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.102"
clap = { version = "=4.5.60", default-features = false, features = ["std"] }
env_logger = "=0.11.9"
log = "=0.4.29"
p384 = { version = "=0.13.1", features = ["ecdsa"] }
serde = "=1.0.228"
serde_derive = "=1.0.228"
sha2 = "=0.10.9"
hex = "=0.4.3"
toml = "=0.7.8"
zerocopy = { version = "=0.8.40", features = ["derive"] }
tempfile = "=3.26.0"
once_cell = "=1.21.3"
memoffset = "=0.9.1"
colored = "=2.2.0"

