# Licensed under the Apache-2.0 license.

# Modified by ASPEED Technology Inc., 2026-05-18: Rename the Rust dependency crate import for compatibility with two versions of the auth manifest 
#                                                 generation tool, and remove unused dependencies: caliptra-drivers and caliptra-image-elf.

[package]
edition = "2021"
name = "caliptra-auth-man-types-1x"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
arbitrary = {workspace = true, optional = true}
bitfield.workspace = true
bitflags.workspace = true
caliptra-image-types-1x = {workspace = true, default-features = false}
caliptra-lms-types-1x.workspace = true
memoffset.workspace = true
zerocopy.workspace = true
zeroize.workspace = true

[features]
default = ["std"]
std = []
