# Licensed under the Apache-2.0 license.

# Modified by ASPEED Technology Inc., 2026-04-15: Rename the Rust dependency crate import for compatibility with two versions of the auth manifest generation tool.
# Modified by ASPEED Technology Inc., 2026-05-18: Remove unused dependencies: caliptra-drivers and caliptra-image-elf.

[package]
edition = "2021"
name = "caliptra-auth-manifest-app-2x"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
caliptra-auth-man-gen-2x.workspace = true
caliptra-auth-man-types-2x = {workspace = true, features = ["std"]}
caliptra-image-crypto-2x.workspace = true
caliptra-image-gen-2x.workspace = true
caliptra-image-serde-2x.workspace = true
caliptra-image-types-2x = {workspace = true, features = ["std"]}
chrono.workspace = true
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_derive.workspace = true
toml.workspace = true
zerocopy.workspace = true

[features]
default = ["openssl"]
openssl = ["caliptra-image-crypto-2x/openssl"]
rustcrypto = ["caliptra-image-crypto-2x/rustcrypto"]
